---
- name: Check for standard /etc/crontab
  shell: grep "system-wide crontab" /etc/crontab
  register: cron_check_standard_crontab
  changed_when: false
  failed_when: false
  tags: skip_ansible_lint

- name: Remove standard /etc/crontab
  file:
    path: /etc/crontab
    state: absent
  when: cron_check_standard_crontab.rc == 0

- name: Configuring crontab tasks
  cron:
    cron_file: "/etc/crontab"
    user: "root"
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
  with_items: "{{ cron_crontab_tasks }}"
  tags: [ cron ]

- name: Configuring crontab variables
  cronvar:
    cron_file: "/etc/crontab"
    user: "root"
    name: "{{ item.name | default(omit) }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
  with_items: "{{ cron_crontab_vars }}"
  tags: [ cron ]
